version: 39
jobs:
- name: maven ci
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !GenerateChecksumStep
    name: generate pom checksum
    files: '​**​/pom.xml'
    targetFile: checksum
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetupCacheStep
    name: set up maven cache
    key: maven_repository_@file:checksum@
    loadKeys:
    - maven_repository
    paths:
    - /root/.m2/repository  # 修正为容器内路径
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run tests
    runInContainer: true
    image: maven:3.3.9-jdk-8  # 指定 Maven 3.3.9 + JDK 8 镜像
    interpreter: !DefaultInterpreter
      commands: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        mvn clean test -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  # 其余步骤保持不变...
  - !SetBuildVersionStep
    name: set build version
    buildVersion: '@file:buildVersion@'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishJUnitReportStep
    name: publish unit test report
    reportName: Unit Test
    filePatterns: '**/TEST-*.xml'
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger {}
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
