version: 39
jobs:
- name: maven ci
  steps:
  - !CheckoutStep
    name: checkout code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !GenerateChecksumStep
    name: generate pom checksum
    files: ​**​/pom.xml
    targetFile: checksum
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetupCacheStep
    name: set up maven cache
    key: maven_repository_@file:checksum@
    loadKeys:
    - maven_repository
    paths:
    - /root/.m2/repository
    uploadStrategy: UPLOAD_IF_NOT_HIT
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: run tests
    runInContainer: true
    image: maven:3.3.9-jdk-8
    interpreter: !DefaultInterpreter
      commands: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        mvn clean test -Dmaven.compiler.source=1.8 -Dmaven.compiler.target=1.8
    useTTY: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !SetBuildVersionStep
    name: set build version
    buildVersion: '1.0'
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PublishJUnitReportStep
    name: publish unit test report
    reportName: Unit Test
    filePatterns: '**/TEST-*.xml'
    condition: ALWAYS
    
     # 新增：部署到远程服务器
  - !CommandStep
    name: deploy to server
    runInContainer: true
    image: appropriate/scp # 使用支持 SCP 的镜像
    environment:
      - SERVER_USER: My
      - SERVER_IP: 45.207.197.85
      - SERVER_PATH: /root/test
    secrets:
      - DEPLOY_KEY: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcnNhAAAAAwEAAQAAAgEA6ruOdKs2EqDJOBZ7+NVpC8//Ou1ifl1E3I2lZ1WZfEYA642+2QwFCIsjoTd7SzzDWRBClw1damOupzH8dhvpvcE3YrNNvDfkjxaCa32614xeDbPxwuZ0mYoBwsMzlWU48oS1mNtYElR4Lc3M8ZlC7k5aKBVZqqqH5MQdj8SXwsbWIbmoJXKDB6WyqAUB7oHbuOfMOuX87cYzDWmgnHmmfQTqMFoa2vHAMshxjyD6iEYC4J5tYO9e/dzk9EfZKEXBlUmJ6Es+qrnSvLJ2OqSaUSLeb4UDTtqG6smXjGKL5DR2LRyeURs2abjNG4VXEKWph4n9ZLKQ6C/t/SashKCbzQZcV9HMoX67Mnz2rzM4DdYsefZmvWXOBDBDiW6OVakLF3kHu3v1ZDh+iH6k3si2yuIsIbZ3OAJEpjfXBPDbnOlpbWN2cjxT8KAz38TeKXpkAn1l7e4vOtyTMJXuxhg6lZa1Lt7bwli+gmY1W6bmS8fOnyNG3SJlyjhFz669c9kyC5Tobs2FP+IRtvuDLyAutNeZop8Y2NDSUbab3cbSycs/bl0+z9hmTzrorusCyAakTm1S4v89eU+ytLl+9wVkUPkSqDCnzbibMdYsXNpsVtQDp8uMe3uYFM43n6V+YOvWEYUfeEli4WzNwG1wYewYwPPLk8+V985r6oG2JulFotcAAAdQMvZ/LzL2fy8AAAAHc3NoLXJzYQAAAgEA6ruOdKs2EqDJOBZ7+NVpC8//Ou1ifl1E3I2lZ1WZfEYA642+2QwFCIsjoTd7SzzDWRBClw1damOupzH8dhvpvcE3YrNNvDfkjxaCa32614xeDbPxwuZ0mYoBwsMzlWU48oS1mNtYElR4Lc3M8ZlC7k5aKBVZqqqH5MQdj8SXwsbWIbmoJXKDB6WyqAUB7oHbuOfMOuX87cYzDWmgnHmmfQTqMFoa2vHAMshxjyD6iEYC4J5tYO9e/dzk9EfZKEXBlUmJ6Es+qrnSvLJ2OqSaUSLeb4UDTtqG6smXjGKL5DR2LRyeURs2abjNG4VXEKWph4n9ZLKQ6C/t/SashKCbzQZcV9HMoX67Mnz2rzM4DdYsefZmvWXOBDBDiW6OVakLF3kHu3v1ZDh+iH6k3si2yuIsIbZ3OAJEpjfXBPDbnOlpbWN2cjxT8KAz38TeKXpkAn1l7e4vOtyTMJXuxhg6lZa1Lt7bwli+gmY1W6bmS8fOnyNG3SJlyjhFz669c9kyC5Tobs2FP+IRtvuDLyAutNeZop8Y2NDSUbab3cbSycs/bl0+z9hmTzrorusCyAakTm1S4v89eU+ytLl+9wVkUPkSqDCnzbibMdYsXNpsVtQDp8uMe3uYFM43n6V+YOvWEYUfeEli4WzNwG1wYewYwPPLk8+V985r6oG2JulFotcAAAADAQABAAACACE5QsSIpzKjx1dE928U5bViT0HL77DrCqAc/FhP6VWJov+0JFscNGotJ3HeJHlVtGCayJIQtjQkv8eyb4VYFhFhk7FIp6wITTVjfjowpY10tKtD2Og5Li+9NNqYPmja1uCcoAdupFyT0B7LjkJz6uFH/cLGotZhJLLgfz6mGMTc19oWKRKDzr/6V/soGknj33GgfWuouc/9yaQQW0dKgKIZW/xUBJEQvp9xd4FGra80GZwpUFn0B4HvDgj1Ums81FWI/xf97nTDsGw85jcOrTjmso0eSoWSsJ3ywpyAJkS6mC9yaYYZT+5O1dkbWmNkz0X75f2muJPklM7L9ocfJG3vHfLo1puwChyhdegCTEPtKm4LE5Q5tRj9uNgwqudyDwcvyVR6JIDU3ja9zQqHQekVw3mGATzoofHU8qs+zWy4AibzrgdFiTaJKWJxm84wWLfs8zFU6t4DtJQQhFFv6suZYmoR4wYl+zIKlgu6Hb5Kb7RSYBYzEEmB9y7u/++pm6UdhJR079mViJmOxKtZFQjhI6bfIV4G0rdYtwPbC3BneVQYAQJsB72onz3nG9HBTP0nQOC2mzGasx9hbWFJEAB8xK2AIeYPadW+Ud3aNOTjQnZtAC3Ob9N0ft63HTCM4JWFw8LXR/APEKiAhCiUek0prIqQ+cPt7GdURg9PD8vBAAABAQD4EoD/H8MRwIVyac0MlioIcdYl4Bom7UL5tPPGIGmlRvtKA/1eU/YJVWjOm8HZweCtBXimbYc5ByoF2eSoRxq3IsT5fhEFgefFiYfdORe7QhUUE/ubjRI5UMwccG01JusABeV8ZK20bMMc42AlMjdNcJ9zyN8Ru2AHPZ/LqJl6YY62AsFeFju9Dw8vsBR7emOZBnxf00ivcTwWKb5zzViLLCh2JFdiMGQHlqiRLhR+HjfbEnw6G2GroMICguLC3ZZ8ufCw+4qbl7/XuygWlDtEUIdVtalyP+ywhrXXpuywT8y0l3ClqP9CeXB34SDBq+1cvu5loiR0V048ddvXemxoAAABAQD4wZNVm9vhDifsyU7/q3Ue31efkMK9idvN37q6n3UE5VSVfxUTvI6dWk+DSq/EV2xgADE20KwHMU1sVkFOdcacTe8Sv78lnIckw1er7hAN3+PdxhG2Ni7Cw/nXF0QY9/CgFr6HE8mMR91abkI+hzZ2M/7ReoEsLET1UMuXsk6wpH5eZA+wnDHEZ43n/aEz74eviy02gAy9otO5xuyaV0aTsFZCjPWiOaHueaKjHz02rU5vubqKk1AzUB+8uhQlvyXVItB2rynrF9YaonJ6M54evWhXRtDO40SxjYm+wsmNiEFSdMM9e4pmER7elVcTuDW6tCsMg9C/Mnvy1jPTRX65AAABAQDxkXBKB81FM7OV9UGBsw/me/ZciA+07MNMJnyjuv1tUxkjU4tD4De0/+oNBWSo2FmMwP0nJmlEE5wqNLLQabbMwI8LXDTsF3OSn8pcU1kBdzI6MrrERq6/jBoDYoxeFLwHyNg2vl3j8KCxCGNBeQOmqVe7/AhrD8bFwMaKi5GFaX0QRkbI5K4ljXvHEZV92AQHzqbJoA0XP+F3heKnz20O4wEbGxmMVNAsLKHodlceKEcTnuY8CTPgiEddyHRNq7/RVMoD82QR9ZUh4h1DxmFF6AlgcKRro97lSyt7w+FGNQTmki7yN0hC4YOb+V651EzaG2Bw0cTRnb52qRiWoeYPAAAAFnlvdXJfZW1haWxAZXhhbXBsZS5jb20BAgME

    interpreter: !DefaultInterpreter
      commands: |
        echo "$DEPLOY_KEY" > /tmp/id_rsa && chmod 600 /tmp/id_rsa # 将私钥写入临时文件
        scp -i /tmp/id_rsa target/*.jar $SERVER_USER@$SERVER_IP:$SERVER_PATH # 使用 SCP 传输打包文件
        ssh -i /tmp/id_rsa $SERVER_USER@$SERVER_IP "bash -s" < ./path/to/start-script.sh # 执行远程启动脚本
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
    
  triggers:
  - !BranchUpdateTrigger {}
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
